# Generated by Django 2.0.6 on 2019-02-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_mobile', models.CharField(default='', max_length=20, null=True)),
                ('user_landmark', models.CharField(default='', max_length=20, null=True)),
                ('user_city', models.CharField(default='', max_length=20, null=True)),
                ('user_state', models.CharField(default='', max_length=20, null=True)),
                ('user_pincode', models.CharField(default='', max_length=20, null=True)),
                ('user_image', models.CharField(default='', max_length=20, null=True)),
                ('user_isactive', models.BooleanField(default=True)),
                ('user_billaddress', models.CharField(default='', max_length=20, null=True)),
                ('user_gender', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='roleid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.UserRole'),
        ),
    ]
