# Generated by Django 2.0.6 on 2019-03-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(default='', max_length=225)),
                ('doctor_address', models.CharField(default='', max_length=500)),
                ('doctor_email', models.EmailField(max_length=225)),
                ('doctor_phone', models.CharField(max_length=225)),
                ('doctor_photo', models.CharField(max_length=225)),
                ('doctor_gender', models.CharField(max_length=10)),
                ('doctor_department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.Department')),
            ],
        ),
    ]
