# Generated by Django 2.0.6 on 2019-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_strength',
            field=models.IntegerField(null=True),
        ),
    ]
