# Generated by Django 2.0.6 on 2019-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190301_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_phone',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
