# Generated by Django 2.0.6 on 2019-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190301_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(default='', max_length=224)),
                ('member_address', models.CharField(default='', max_length=224)),
                ('member_email', models.EmailField(default='', max_length=224)),
                ('member_phone', models.CharField(default='', max_length=225)),
                ('member_image', models.CharField(default='', max_length=225)),
                ('member_gender', models.CharField(default='', max_length=225)),
                ('member_status', models.BooleanField(default=True)),
            ],
        ),
    ]
