# Generated by Django 2.0.6 on 2019-03-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='member_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='member_image',
            field=models.CharField(default='', max_length=225, null=True),
        ),
    ]
