# Generated by Django 2.0.6 on 2019-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190302_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_password',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='member_password',
            field=models.CharField(max_length=1100, null=True),
        ),
    ]
