# Generated by Django 2.0.6 on 2019-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190302_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_first_name',
            field=models.CharField(default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_last_name',
            field=models.CharField(default='', max_length=225, null=True),
        ),
    ]
