# Generated by Django 2.0.6 on 2019-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190302_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='member_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='member_first_name',
            field=models.CharField(default='', max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='member_last_name',
            field=models.CharField(default='', max_length=225, null=True),
        ),
    ]
