# Generated by Django 2.0.6 on 2019-03-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190303_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.UserRole'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.UserRole'),
        ),
    ]
